apiVersion: v1
data:
  public: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUNDZ0tDQWdFQXlJYmJvUUFrbGk2Zm1oZDhyWk9HQU10ZnBsamhreUlqMzl6cENmeXIyZHJyclpadXdKcVYKdjFJYVZpNHRqbkpVc0ZRYTMvVUxBMDk0NXVRdGcrY1NWWkFPL3dCUEVLU0pyQXp6a0h6RUZaVjRQdzNBdGtwUwpsaU9JMkg5bEUyeHF6TjdlSkoxLytIbXhwNGhxYWo4cTl0N21rOTR0SWxWbENLNGE3aGt5bUtUa3JLRHo2V2IyCllPOXc2S3dsdGx5OHRDZ3pjSnVUTDUyK2w2QURRc213cGdZVldQQjVtR05ORi9IQlRKd1IzbkpQODlzTjlkc2MKQm5YRCtvcXprbXZOKzYzeTY1L0xnZS84a0R3cHRhNDloUGFObEU4dUwrbEtOZ0hRbjV6cURkRWRDTjhiVTMvRgp3UzZWSnVlMFBYaE9YZkt4MnVSS0trU1pkWGZ1RzN5b20wWHkvazV2c0V5ZUUrOFliOXNIa1VOK2FUQ0tGbDBnCkdOSDBFVkRpdjMrNlE5RlYrNnVKbDBNaE1rVjJtNXVna2tUdHpLc0g0dHNSbnZLUyt5ZlBjQUpjcE9uODl5YVcKc0pUR2F2Q0xNYXVJWDVsT3VreEo2Zm00U1lJd1R2WUo0MVpFQkRjQk5EWnZOdVZGdFcrY3NYR2NWalE1QldHZgpjOTJacVI4M2tSUVEzVVZkUmtNcjl2d0s1OUlxMFoxQTB5Ri9qR1FqVzQybTlsN1JvbFErcEhTbkdjN0o5VlROCjhOZVZzQkFsRElpQ0wrVUIwbm5ic3ZjQ2RnbUpqbHczclRZTkVTYnRPME1EalRFOFhXZVJxVDZvblF2c3NtZmEKME9zY3pwTlF0VXZ0Zk0zM3IyZEp1ODZBVU5FeEFSRThOUjhKMjJ0eTd3eXFVMXlSeGVmR3VSTUNBd0VBQVE9PQotLS0tLUVORCBSU0EgUFVCTElDIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: "2022-05-09T01:26:54Z"
  name: ctlog-public-key
  namespace: default
  resourceVersion: "5178"
  uid: e8d96050-8eb2-4840-b8f1-662f0233811b
type: Opaque
